# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7311719452317e0f7bf6da1e7dca9b4de9042e3df08a9f38fda7593fe2e215601d43bf46574c2957838c6029ba85ee13197fe683af8dcd063ef01cb22f27ec02

test:
  secret_key_base: 0b845aec01d0bd2107cbe2e00aed52ef0255402ac755cfb998093926d1a5905e3c0826fb8a8ad7ba111225a58c011fe962cac1f58e4e5af431da233fced2eddb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
